### PR TITLE
Added new quest: Is this barrier (usally) locked?

### LINKED ISSUE #474: New Quest: What is the access at this gate/barrier?
### General
Affected tag(s) to be modified/added: [access](https://wiki.openstreetmap.org/wiki/Key:access) or [locked](https://wiki.openstreetmap.org/wiki/Key:locked) and/or [gate:type](https://wiki.openstreetmap.org/wiki/Key:[access](gate:type))
Question asked: **What is the access at this gate/barrier?**

### Abstract

I add a lot of barriers to OpenStreetMap when I see them in the aerial photography. These can be lift_gate's, gate's or other barriers. You can't see the `access` from the aerial photo, this would have to be done on site.

Here I would like to start a small collection of ideas, how exactly the filter could look like and which values make sense when.

The goal should be that one supplements the appropriate access at barriers, which can be closed for some transport modes in some kind. This helps routing software to decide depending on the means of transport whether this may pass through here.

**Element selection:** 
```
nodes with barrier
and (
!access or !bicycle or !foot or !motor_vehicle
)
```

**Metadata needed:** 

**Proposed UI:**
A multi selection should be considered to select more than one access-value. Maybe also the recycling quest would be suitable, but with an major option for `access=all`.

What do you folks think about this?

### PR DESCRIPTION
**Pull request by mcliquid**
Fixes #474 

- simple quest: Just ask if a barrier is locked (Answer is Yes or No)
- barrier selection is based on most used combinations of `locked=yes` with `barrier=*`
- I've removed `barrier=lift_gate` from the elementFilter as most of them I know are automatic and not manual
- quest will be asked after 5 years if `locked=yes` and after 10 years also for `locked` in general
- SCEE users can modify the elementFilter if needed

### CODE REVIEW

**Comment by Helium314** [comment]
It's good, but missing an other answer for time restriction input, which I think is quite commonly needed e.g. for park gates.
Though I'm not sure how to tag this. `locked:conditional` is documented in the wiki, but `opening_hours` seems to be used more often.

If you want, you can try to essentially copy the `AddParkingFeeForm` without code related to `MAX_STAY`.
It might be quite simple, or you might run into weird troubles... anyway I can add this myself if you prefer.

**Comment by mnalis** [comment]
> `locked:conditional` is documented in the wiki, 

Uh, no, it isn't, as far as I can see? 

https://wiki.openstreetmap.org/wiki/Tag:locked:conditional is on-the-fly auto-generated wiki magic which  is shown for any undocumented key containing `:`, where it tries to find if separate components exists and show taginfo usage (e.g. you'll get similar page for https://wiki.openstreetmap.org/wiki/Tag:foo:bar:baz or any other made-up tag)

> but `opening_hours` seems to be used more often.

Yeah, `opening_hours` has [3055 uses](https://taginfo.openstreetmap.org/keys/locked#combinations) in combination with `locked`, compared with only [83 uses](https://taginfo.openstreetmap.org/keys/locked#combinations) of undocumented `locked:conditional` with `locked`. So I'd go with `opening_hours` there...

**Comment by Helium314** [comment]
> Uh, no, it isn't, as far as I can see?

https://wiki.openstreetmap.org/wiki/Key:locked

**Comment by Helium314** [comment]
It's even in the approved proposal: https://wiki.openstreetmap.org/w/index.php?oldid=1986160

**Comment by Helium314** [comment]
What I did:
* copy `Fee.kt` and rename to `BarrierLockedAnswer.kt`
* copy the fee quest form, remove stuff related to maxstay and rename
* make the form and quest use `BarrierLockedAnswer` instead of `FeeAndMaxStay`

I only did a short test, but looks like it's working.

**Comment by Helium314** [comment]
Great!
So what's left is which tag to use. I'd prefer`locked:conditional`, even though it has far less usage than `opening_hours`, simply because the meaning is very clear.
`opening_hours` is not documented on `barrier`s, and in my understanding only states when a gate is open, but not that it's necessarily locked outside opening hours.

**Comment by mnalis** [comment]
> It's even in the approved proposal: https://wiki.openstreetmap.org/w/index.php?oldid=1986160

Ah, OK then. I've clarified the use in the wiki and added a redirect for   https://wiki.openstreetmap.org/wiki/Tag:locked:conditional

**Pull request merged**
